services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${DB_USER:-app}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-!ChangeMe!}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER:-app}", "-p${DB_PASSWORD:-!ChangeMe!}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - database_network