services:
  database:
    image: mysql:8.0
    command: --log-bin-trust-function-creators=1
    environment:
      MYSQL_DATABASE: ${DB_NAME:-app}
      MYSQL_PASSWORD: ${DB_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${DB_USER:-app}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-!ChangeMe!}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USER:-app}", "-p${DB_PASSWORD:-!ChangeMe!}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d:ro
    networks:
      - database_network

      
  pride-api:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: npm run dev
    networks:
      - database_network

volumes:
  database_data:

networks:
  database_network: