services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - database_network

  rabbitmq:
    image: rabbitmq:3.8-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - database_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
      
  pride-api:
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - api-send-mail
    command: npm run dev
    networks:
      - database_network

  api-send-mail:
    build: ../MailGo
    ports:
      - "3030:3000"
    command: /app/api
    networks:
      - database_network
    depends_on:
      - rabbitmq

  service-send-mail:
    build: ../MailGo
    command: /app/queue
    networks:
      - database_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      api-send-mail:
        condition: service_started 
      pride-api:
        condition: service_started



volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-log:

networks:
  database_network: