name: Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to GCP
        run:  |
          ssh -o StrictHostKeyChecking=no google@35.199.83.112 \
            "./uap/script/deploy.sh"
    
