name: Run unit test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env: # Define environment variables at the job level
      EMAIL_FROM: email@email.com
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PASSWORD: password # Consider using GitHub Secrets for sensitive data
      EMAIL_PORT: 587
      EMAIL_URL_SERVICE: http://localhost:3000/email/campaigns

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install # Corrected typo
    - run: npm test
